name: Dependabot auto-merge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - test

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ github.actor == dependabot[bot] }}
        run: echo "$GITHUB_CONTEXT"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{github.actor == dependabot[bot] && (steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor')}}
        run: gh pr merge --auto --merge "$PR_URL"
